// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaiDZ2-gqvw05TqRHtr0DX0Xk9WpUiy4g',
    appId: '1:830086493481:web:ae82d4d51b483b5ad63338',
    messagingSenderId: '830086493481',
    projectId: 'wzlot-dfe43',
    authDomain: 'wzlot-dfe43.firebaseapp.com',
    databaseURL: 'https://wzlot-dfe43-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'wzlot-dfe43.appspot.com',
    measurementId: 'G-20NCB3D7CQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSytJUvYuCpMKiZlDgtDJFEeV3qq1WtYc',
    appId: '1:830086493481:android:8f1afb6e6e92c763d63338',
    messagingSenderId: '830086493481',
    projectId: 'wzlot-dfe43',
    databaseURL: 'https://wzlot-dfe43-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'wzlot-dfe43.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaiDZ2-gqvw05TqRHtr0DX0Xk9WpUiy4g',
    appId: '1:830086493481:web:c41215905ddc8629d63338',
    messagingSenderId: '830086493481',
    projectId: 'wzlot-dfe43',
    authDomain: 'wzlot-dfe43.firebaseapp.com',
    databaseURL: 'https://wzlot-dfe43-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'wzlot-dfe43.appspot.com',
    measurementId: 'G-8N4RQQ648C',
  );

}